### PR TITLE
 Using osascript -l javascript to retrieve a proper filepath from fileselect

### PR DESCRIPTION
**Pull request by obando777**
Hello 

osascript is right now returning alias names instead of file names but using javascript it is capable of return a proper absolute filepath.
https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/PromptforaFileorFolder.html

### CODE REVIEW

**Comment by obando777** [comment]
Sorry for using your date picker branch as my basis, but seems to me that this branch is the one that match what i was looking for, Thank you for your contributions on dialog-node.

**Comment by brettz9** [comment]
Nice work, thanks! I've rebased (and just added `node_modules` to `.gitignore`).

I also rebased the `object-api` branch on top of your changes, including changing your code in that branch to use `const`, renaming `str` to `message`, and simplifying the `push` statements, as I did with other code in that branch.

Do you have any problems using the object-api branch (which I think should be superior), or did you just want to ensure your changes made it into the earliest branch where it was relevant? Closing but feel free to comment further.

**Comment by obando777** [comment]
No problem, i will move myself to object api branch, let me know if you have anything in mind or do you want me to test futher contributions of you.

**Comment by brettz9** [comment]
Thanks very much. Hopefully, we'll see these incorporated upstream...

**Comment by obando777** [comment]
I will be up for any plan or idea on a light cross platform prompt lib for
nodejs.

**Comment by brettz9** [comment]
Cool... I don't have anything else in mind at this time, but open to hearing ideas myself...

**Comment by obando777** [comment]
Well the first time i search on internet about this i was expecting something that opens a browser like:
```
using something like https://github.com/sindresorhus/open
open('../node_modules/openPopup.html');
```
and allowing to show a full setup form. 

But i was dreamy i guess, but the idea of automatically render a key, value array with simple validations like validate.js is still around my head. Hahahahaha

**Comment by brettz9** [comment]
That's a very appealing idea...

One could implement this in a few ways I think.

The first has the advantage of being potentially more cross-platform, the first and second have the advantage of possessing the full expressive power of HTML, while the third would not require a particular browser or browser add-on install for your users (though if your use case is mostly for yourself or developers, this might not be so necessary).

1. One could use a browser add-on tied to an executable (including a Node-based one) through [Native Messaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) to allow the browser to communicate back to the calling app. My add-on "webappfind" performs such communication, though typically in the context of reading or writing files in response to a web app, but it could be adapted so that the Node-based web sockets client that it sets up could listen for browser apps being given permission to execute specific executables (or one could leverage what webappfind already supports of requesting Node string eval privileges through WebAppFind's currently bundled "AsYouWish" component). You might see the videos on the [webappfind](https://github.com/brettz9/webappfind) page. If you are interested in this approach, I'd be happy to try to support your use cases as feasible.

2. One could write AppleScript to script a specific browser. See, e.g., http://www.cubemg.com/how-to-click-a-button-on-a-web-page-with-applescript/

3. One could use AppleScript to build more sophisticated dialogs, such as https://computers.tutsplus.com/tutorials/applescript-creating-complex-dialogs-with-ease--mac-27128 .

**Comment by obando777** [comment]
I think your first idea is great, lets do something like that using your webappfind extension first, and later after a few tests, we could think on how make it completely an npm package that works out of the box with just few tweaks. I mean without requiere the user to install an add-on.

**Comment by brettz9** [comment]
On further reflection, I'm thinking that it may make more sense to add dependencies to `dialog-node` for `node-static` and `open-cli`, and just have a method which returns a `Promise` and after starting a static server and opening it, resolves the `Promise` when a particular request is made to the server by the HTML form dialog. This would be cross-platform and cross-browser without modification and work with a standard web request.

**Comment by obando777** [comment]
I agree

**Comment by brettz9** [comment]
I've submitted https://github.com/bat-tomr/dialog-node/pull/11 with an `html` method that I hope will meet your needs. Let me know if you would like further tweaking.

**Comment by obando777** [comment]
I will check that out, i feel grateful of your help

**Pull request closed without merging**
